### ISSUE TITLE
Error with new config file (which does not exist?)

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#18]
Using 3ba59dbf5ae9cd3c1ac126db173a23ba25e427d5 (`v21.10.6-5-g3ba59db`):

```
collectors_1  | [2021-11-14 09:11:30 +0000] [1] [DEBUG] [None] [managers.collectors_manager] Sending status update...
collectors_1  | [2021-11-14 09:11:30 +0000] [1] [DEBUG] [Errno 2] No such file or directory: '/app/storage/id.txt'
collectors_1  | [2021-11-14 09:11:30 +0000] [1] [DEBUG] [None] [managers.collectors_manager] Core responded with: HTTP 0, Cannot read collector config file.
```
Should that file/directory be created on demand? Where should it come from?

No feeds are collected

**Comment by dodancs** [comment]
Hi Sebastian.

This file is supposed to be created initially when the collector node was added for the first time. It is used to keep track of the particular collector (by its id).

Could you please provide logs for the [collector](https://github.com/SK-CERT/Taranis-NG/blob/3ba59dbf5ae9cd3c1ac126db173a23ba25e427d5/src/collectors/api/collectors.py#L12) and [core](https://github.com/SK-CERT/Taranis-NG/blob/3ba59dbf5ae9cd3c1ac126db173a23ba25e427d5/src/core/remote/collectors_api.py#L13) modules? The core API should have called the path `POST: /api/v1/collectors` on the collector added.

**Comment by sebix** [comment]
> This file is supposed to be created initially when the collector node was added for the first time. It is used to keep track of the particular collector (by its id).
Ok, my installation is older than this change.
> This also means that your collector configuration is broken/missing. You may add the file you mentioned (`/app/storage/id.txt`) with the id of the collector as the contents. You can find the collector id in the OSINT source configuration: ![image](https://user-images.githubusercontent.com/1970811/141675978-5f47d518-b155-43bf-8a37-0f2fdb992cc7.png)

Thanks, did that and this step succeeds.

But now I have:
```
core_1        | [2021-11-14 10:43:54 +0000] [12] [DEBUG] [None] Traceback (most recent call last):
core_1        |   File "/app/taranis-ng-core/model/collectors_node.py", line 82, in get_all_json
core_1        |     time_inactive = (datetime.now() - max(nodes[i].created, nodes[i].last_seen))
core_1        | TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```
I assume this is due to a similar change in the collectors' set-up process?

**Comment by sebix** [comment]
After restarting the containers, I get:
```
core_1        | [2021-11-14 10:59:58 +0000] [12] [DEBUG] GET /api/v1/collectors/b10a9391-8ca7-40ce-b0a1-664392df3aff/osint-sources
collectors_1  | [2021-11-14 10:59:58 +0000] [1] [DEBUG] [None] HTTP 404: Got the following reply: 
core_1        | [2021-11-14 10:59:58 +0000] [12] [DEBUG] Closing connection. 
```
Where b10a9391-8ca7-40ce-b0a1-664392df3aff is the ID of the RSS Collector.

**Comment by dodancs** [comment]
> After restarting the containers, I get:
> 
> ```
> core_1        | [2021-11-14 10:59:58 +0000] [12] [DEBUG] GET /api/v1/collectors/b10a9391-8ca7-40ce-b0a1-664392df3aff/osint-sources
> collectors_1  | [2021-11-14 10:59:58 +0000] [1] [DEBUG] [None] HTTP 404: Got the following reply: 
> core_1        | [2021-11-14 10:59:58 +0000] [12] [DEBUG] Closing connection. 
> ```
> 
> Where b10a9391-8ca7-40ce-b0a1-664392df3aff is the ID of the RSS Collector.

It seems that the id you set is incorrect. See how the [collector checks if the collector node exists](https://github.com/SK-CERT/Taranis-NG/blob/3ba59dbf5ae9cd3c1ac126db173a23ba25e427d5/src/core/api/collectors.py#L58). Please doublecheck if you set the correct id.

Another option would be to re-add the collector.

@milankowww Maybe we could add a button in the GUI to re-initialize the collector node.

**Comment by milankowww** [comment]
Since this situation does not affect new installations, I don't suppose adding a "fix me" button is way to go.

@sebix please try this to fix the issue, and let me know if it works:

```bash
echo 'select id from collectors_node limit 1' | \
    docker exec -i taranis-ng_database_1 psql  -Utaranis-ng -A --csv -t | \
    docker exec -i taranis-ng_collectors_1 sh -c 'read X ; echo -n "$X" > /app/storage/id.txt'
```

**Comment by sebix** [comment]
For whatever reason, it works with your solution. Pasting the same id into the file manually didn't do the trick. Maybe a issue with newlines or so, or not enough container restarts.

Anyway: Thanks for the support, my installation works again and new requests will follow :)

**Comment by dodancs** [comment]
@sebix Sorry for the troubles. In the next release (v.21.11.1) there will be the updated `manage.py` script which can do re-initialization of collector nodes with just one command - [see here](https://github.com/SK-CERT/Taranis-NG/tree/main/docker#re-initialize-a-collector-node).

**Comment by sebix** [comment]
Thanks for the help.

I'm fully aware that the software is not yet fully stable, although I hope that you have at least some benefit of my early beta-testing :)

**Comment by dodancs** [comment]
> Thanks for the help.
> 
> I'm fully aware that the software is not yet fully stable, although I hope that you have at least some benefit of my early beta-testing :)

For sure, it helps a lot! Thank you.
