### ISSUE TITLE
Cant Configure the collector

### ISSUE THREAD

**Issue by merlin-ke** [SK-CERT/Taranis-NG#256]
I keep getting this error after running docker composer up. Default collector isn't setup
```
collectors-1  | [2024-04-08 14:44:15 +0300] [7] [DEBUG] [Errno 2] No such file or directory: '/app/storage/id.txt'
collectors-1  | [2024-04-08 14:44:15 +0300] [7] [WARNING] [None] configuration not received, code: 0, response: Cannot read collector config file.
collectors-1  | [2024-04-08 14:44:15 +0300] [7] [INFO] [None] Core API requested a refresh of osint sources for SCHEDULED_TASKS_COLLECTOR...
collectors-1  | [2024-04-08 14:44:15 +0300] [7] [DEBUG] [Errno 2] No such file or directory: '/app/storage/id.txt'
collectors-1  | [2024-04-08 14:44:15 +0300] [7] [WARNING] [None] configuration not received, code: 0, response: Cannot read collector config file.
```

**Comment by hsninbil** [comment]
-	STEP 1: open terminal, and update the configuration:
cd Taranis-NG
            docker build -t taranis-ng-bots . -f ./docker/Dockerfile.bots
            docker build -t taranis-ng-collectors . -f ./docker/Dockerfile.collectors
           docker build -t taranis-ng-core . -f ./docker/Dockerfile.core
           docker build -t taranis-ng-gui . -f ./docker/Dockerfile.gui
           docker build -t taranis-ng-presenters . -f ./docker/Dockerfile.presenters
           docker build -t taranis-ng-publishers . -f ./docker/Dockerfile.publishers

- [ ] Taranis NG instance is up and running.

-	STEP 2: open the web browser by navigating to https://@IP:4443. The default credentials are admin / admin.
-	STEP 3: to Add a collector, then navigate to Configuration -> Collectors nodes. You should see Default Docker Collector in the list. Or you can add a new collector (figure 1 and 2)
![collector-nod](https://github.com/SK-CERT/Taranis-NG/assets/14868613/3eb994b3-8c6e-4a0b-b508-2f8ccd11b931)
<img width="691" alt="Screenshot 2024-04-14 151305" src="https://github.com/SK-CERT/Taranis-NG/assets/14868613/c965d72e-5b93-4beb-8631-144b6d983ef2">

-STEP 4: Adding a presenter node. Go to Configuration -> Presenters nodes. Click Add new. Enter any name and description. For URL, enter http://presenters/ and for key, enter supersecret (or whatever password you chose during the installation). Click Save.
- STEP 5 : Adding a publisher node: Configuration -> Publishers nodes. Click Add new. Enter any name and description.   For URL, enter http://publishers/. and for key, enter supersecret (or whatever password you chose during the installation). Click Save
STEP 6 : Adding sources to collect. Configuration -> OSINT Sources. Click Add new. Select the collectors node that you just created and then you should be able to see all the collectors it has registered. Pick one (for instance the RSS collector), and you will be able to enter all the necessary details. Finally, click Save.
STEP 7: Uploading the CPE, CWE and CVE dictionaries (https://github.com/SK-CERT/Taranis-NG/tree/main)

**Comment by ByteMastermind** [comment]
> * STEP 1: open terminal, and update the configuration:
>   cd Taranis-NG
>   docker build -t taranis-ng-bots . -f ./docker/Dockerfile.bots
>   docker build -t taranis-ng-collectors . -f ./docker/Dockerfile.collectors
>   docker build -t taranis-ng-core . -f ./docker/Dockerfile.core
>   docker build -t taranis-ng-gui . -f ./docker/Dockerfile.gui
>   docker build -t taranis-ng-presenters . -f ./docker/Dockerfile.presenters
>   docker build -t taranis-ng-publishers . -f ./docker/Dockerfile.publishers
> * [ ]  Taranis NG instance is up and running.
> * STEP 2: open the web browser by navigating to https://@ip:4443. The default credentials are admin / admin.
> * STEP 3: to Add a collector, then navigate to Configuration -> Collectors nodes. You should see Default Docker Collector in the list. Or you can add a new collector (figure 1 and 2)
>   ![collector-nod](https://private-user-images.githubusercontent.com/14868613/322272367-3eb994b3-8c6e-4a0b-b508-2f8ccd11b931.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTk0NzQsIm5iZiI6MTcxMzI1OTE3NCwicGF0aCI6Ii8xNDg2ODYxMy8zMjIyNzIzNjctM2ViOTk0YjMtOGM2ZS00YTBiLWI1MDgtMmY4Y2NkMTFiOTMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MjYyMTBmZjVmNzAyMzJiNWU4ZDcwNTE0OGY3NzBkYmMwYTdhMTk3NjhiMDk2MGNiNmU0YzQ0OTUyNWJiZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ENE1lbYY_NUR-JhQ_PRDWuKttfRL5cvDMmispLs2NyA)
> 
> <img alt="Screenshot 2024-04-14 151305" width="691" src="https://private-user-images.githubusercontent.com/14868613/322272387-c965d72e-5b93-4beb-8631-144b6d983ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTk0NzQsIm5iZiI6MTcxMzI1OTE3NCwicGF0aCI6Ii8xNDg2ODYxMy8zMjIyNzIzODctYzk2NWQ3MmUtNWI5My00YmViLTg2MzEtMTQ0YjZkOTgzZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNWIzZTE3OTgwNGQxNThiYTYwY2ZkYjc1NDRhY2EzNTQ1MDYwYTVlYmY2MmQ2NDk3ZjQyMjRlYmRlOTU0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zt90S_arq5M_DIQ-BhXEQuyFxXEmbIDA1Mf4rqQY6xM">
> -STEP 4: Adding a presenter node. Go to Configuration -> Presenters nodes. Click Add new. Enter any name and description. For URL, enter http://presenters/ and for key, enter supersecret (or whatever password you chose during the installation). Click Save.
> 
> * STEP 5 : Adding a publisher node: Configuration -> Publishers nodes. Click Add new. Enter any name and description.   For URL, enter http://publishers/. and for key, enter supersecret (or whatever password you chose during the installation). Click Save
>   STEP 6 : Adding sources to collect. Configuration -> OSINT Sources. Click Add new. Select the collectors node that you just created and then you should be able to see all the collectors it has registered. Pick one (for instance the RSS collector), and you will be able to enter all the necessary details. Finally, click Save.
>   STEP 7: Uploading the CPE, CWE and CVE dictionaries (https://github.com/SK-CERT/Taranis-NG/tree/main)

Followed aforementioned steps, however, no **Default Collector** is in the list, and no new collector node can be added (entered same values as in your picture and the same key - was not changed).

Any ideas?

**Comment by ByteMastermind** [comment]
> @ByteMastermind @merlin-ke It happened to me. I retry to rebuild (docker-compose), if you are using the docker-compose
> 
> ARANIS_NG_TAG=build docker-compose -f docker/docker-compose.yml build --pull TARANIS_NG_TAG=build docker-compose -f docker/docker-compose.yml up
> 
> or this if you have use the docker
> 
> TARANIS_NG_TAG=build docker compose -f docker/docker-compose.yml build --pull TARANIS_NG_TAG=build docker compose -f docker/docker-compose.yml up

Seems like the problem still prevails.

**Comment by merlin-ke** [comment]
I managed to solve this issue. I opted to build the images using @hsninbil approach. After this, I edited the compose file and updated the image names.  I added a password to Postgre on the file too (of course this isn't recommended ). 
Here is the compose file. After which 

> docker compose up

Brought up everything.

> change the URL from localhost to either an IP or something else otherwise you wont login if you don't access be UI from localhost. This is changed from the .env file.

`services:
  redis:
    image: "redis:${REDIS_TAG}"
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    volumes:
      - "redis_conf:/usr/local/etc/redis"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  database:
    image: "postgres:${POSTGRES_TAG}"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "taranis-ng"
      POSTGRES_USER: "taranis-ng"
      POSTGRES_PASSWORD:  "supersecret"
      TZ: "${TZ}"
      PGTZ: "${TZ}"
    command: ["postgres", "-c", "shared_buffers=${DB_SHARED_BUFFERS}", "-c", "max_connections=${DB_MAX_CONNECTIONS}"]
    volumes:
      - "database_data:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
       - postgres_password

  core:
    depends_on:
      - "redis"
      - "database"
    restart: unless-stopped
    image: "taranis-ng-core:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.core
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        http_proxy: "${HTTP_PROXY}"
        https_proxy: "${HTTPS_PROXY}"
    environment:
      REDIS_URL: "redis://redis"
      DB_URL: "database"
      DB_DATABASE: "taranis-ng"
      DB_USER: "taranis-ng"
      DB_POOL_SIZE: 100
      DB_POOL_RECYCLE: 300
      DB_POOL_TIMEOUT: 30
      TARANIS_NG_AUTHENTICATOR: "${TARANIS_NG_AUTHENTICATOR}"
      LDAP_SERVER: "${LDAP_SERVER}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_CA_CERT_PATH:

      OPENID_LOGOUT_URL: ""
      WORKERS_PER_CORE: "1"

      CVE_UPDATE_FILE: "${CVE_UPDATE_FILE}"
      CPE_UPDATE_FILE: "${CPE_UPDATE_FILE}"
      CWE_UPDATE_FILE: "${CWE_UPDATE_FILE}"

      TZ: "${TZ}"
      DEBUG: "true"
      DEBUG_SQL: "false"
    labels:
      traefik.enable: "true"
      traefik.http.services.taranis-api.loadbalancer.server.port: "80"

      traefik.http.routers.taranis-api-443.entrypoints: "websecure"
      traefik.http.routers.taranis-api-443.rule: "PathPrefix(`/api/`)"
      traefik.http.routers.taranis-api-443.tls: "true"
      traefik.http.routers.taranis-api-443.tls.domains[0].main: "${TARANIS_NG_HOSTNAME}"
      traefik.http.routers.taranis-api-443.service: "taranis-api"

      traefik.http.routers.taranis-sse-443.entrypoints: "websecure"
      traefik.http.routers.taranis-sse-443.rule: "PathPrefix(`/sse`)"
      traefik.http.routers.taranis-sse-443.tls: "true"
      traefik.http.routers.taranis-sse-443.tls.domains[0].main: "${TARANIS_NG_HOSTNAME}"
      traefik.http.routers.taranis-sse-443.service: "taranis-api"
    volumes:
      - "core_data:/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - postgres_password
      - jwt_secret_key
      - api_key

  bots:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "taranis-ng-bots:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.bots
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        http_proxy: "${HTTP_PROXY}"
        https_proxy: "${HTTPS_PROXY}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      TARANIS_NG_CORE_SSE: "http://core/sse"
      WORKERS_PER_CORE: "1"
      TZ: "${TZ}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - api_key

  collectors:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "taranis-ng-collectors:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.collectors
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        http_proxy: "${HTTP_PROXY}"
        https_proxy: "${HTTPS_PROXY}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      WORKERS_PER_CORE: "1"
      DEBUG: "true"
      TZ: "${TZ}"
    volumes:
      - "collector_storage:/app/storage"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - api_key

  presenters:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "taranis-ng-presenters:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.presenters
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        http_proxy: "${HTTP_PROXY}"
        https_proxy: "${HTTPS_PROXY}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      WORKERS_PER_CORE: "1"
      TZ: "${TZ}"
    ports:
      - "${PRESENTER_PORT}:80"
    volumes:
      - "presenters_templates:/app/templates/user_templates"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - api_key

  publishers:
    depends_on:
      core:
        condition: service_healthy
    restart: unless-stopped
    image: "taranis-ng-publishers:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.publishers
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        http_proxy: "${HTTP_PROXY}"
        https_proxy: "${HTTPS_PROXY}"
    environment:
      TARANIS_NG_CORE_URL: "http://core"
      WORKERS_PER_CORE: "1"
      TZ: "${TZ}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - api_key

  gui:
    depends_on:
      - "core"
    restart: unless-stopped
    image: "taranis-ng-gui:${TARANIS_NG_TAG}"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.gui
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        http_proxy: "${HTTP_PROXY}"
        https_proxy: "${HTTPS_PROXY}"
#    ports:
#      - "8080:80"
    environment:
      NGINX_WORKERS: "4"
      NGINX_CONNECTIONS: "16"
      VUE_APP_TARANIS_NG_URL: "${TARANIS_NG_HTTPS_URI}"
      VUE_APP_TARANIS_NG_CORE_API: "${TARANIS_NG_HTTPS_URI}/api/v1"
      VUE_APP_TARANIS_NG_CORE_SSE: "${TARANIS_NG_HTTPS_URI}/sse"
      VUE_APP_TARANIS_NG_LOCALE: "${VUE_APP_TARANIS_NG_LOCALE}"
      TZ: "${TZ}"
    labels:
      traefik.enable: "true"
      traefik.http.services.taranis-gui.loadbalancer.server.port: "80"

      traefik.http.middlewares.redirect-to-443.redirectscheme.scheme: "https"
      traefik.http.middlewares.redirect-to-443.redirectscheme.port: "${TARANIS_NG_HTTPS_PORT}"

      traefik.http.routers.taranis-gui-80.entrypoints: "web"
      traefik.http.routers.taranis-gui-80.rule: "PathPrefix(`/`)"
      traefik.http.routers.taranis-gui-80.middlewares: "redirect-to-443"

      traefik.http.routers.taranis-gui-443.entrypoints: "websecure"
      traefik.http.routers.taranis-gui-443.rule: "PathPrefix(`/`)"
      traefik.http.routers.taranis-gui-443.tls: "true"
      traefik.http.routers.taranis-gui-443.tls.domains[0].main: "${TARANIS_NG_HOSTNAME}"
      traefik.http.routers.taranis-gui-443.service: "taranis-gui"

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  traefik:
    depends_on:
      - "gui"
      - "core"
    restart: unless-stopped
    image: "traefik:latest"
    environment:
      TZ: "${TZ}"
    ports:
      - "${TARANIS_NG_HTTP_PORT}:80"
      - "${TARANIS_NG_HTTPS_PORT}:443"
      - "${TRAEFIK_MANAGEMENT_PORT}:9090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/traefik:ro"
      - "./tls:/opt/certs"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  jwt_secret_key:
    file: ./secrets/jwt_secret_key.txt
  api_key:
    file: ./secrets/api_key.txt

volumes:
  redis_conf:
  database_data:
  core_data:
  presenters_templates:
  collector_storage:`
