### ISSUE TITLE
Feature Request: Virtual (global) group to show all news items in Assess tab

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#27]
An idea:

Additional to the defined OSINT groups, a virtual "global" or "all" group could show all news items from all sources and groups. This could also be the default group to show initially.

**Comment by milankowww** [comment]
This doesn't work well with the intended use case. If you don't require groups, you can either make only one, or make an `all` group where you have all the sources.

Also, because of ACLs this would not be an easy feature to implement.

**Comment by sebix** [comment]
Sad to hear that. Such a virtual global group would be perfect for searching across all groups.
