### ISSUE TITLE
Viewing a news item resets news item selection

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#29]
- In Assess tab, switch to selection mode
- select one or more news items
- open a news item to read the text
- close the news item to go back to the list
- news item list refreshes and the selection vanishes

(same for using keyboard shortcuts)

**Comment by milankowww** [comment]
the short cuts have been changed; needs re-testing on the current HEAD, which at time of writing is 15084b894b7b4b233bb867c65de78ce164cfacce

**Comment by sebix** [comment]
fixed by #40 by myself. I forgot to mention the issue number in the commit
