### ISSUE TITLE
Removing a source from a group does not remove news items from the group

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#32]
I had accidentally a source assigned to two groups, so I removed it from one of them. The news items collected until then are still visible in the assess-Tab.

**Comment by milankowww** [comment]
This is an intentional feature. Preserving pre-existing work done before some reassignments were done is important. This also opens a can of worms with upvotes and permissions.

The news items can be deleted from GUI using multi-select, which solves your problem.
