### ISSUE TITLE
Feature request: Trigger fetching an OSINT source manually, show result

### ISSUE THREAD

**Issue by sebix** [SK-CERT/Taranis-NG#7]
For testing or debugging purpose it would be very handy if it would be possible to trigger that a feed is fetched just right now. Even cooler would be to show the result, e.g. if the fetch succeeded or what the response was if not.

**Comment by dodancs** [comment]
@sebix Hi Sebastian. Thank you for your request.

Implementing proper debugging output as well as collector status, manual collection trigger, plus GUI options to view health information about the application are already on our schedule.

Please be patient :)

**Comment by sebix** [comment]
The collectors already log a lot, when they start, the interval, fetched articles, errors. I think that is enough for now, so I'm closing here. Thanks for implementing the improvements!
