### ISSUE TITLE
No admin user when starting containers

### ISSUE THREAD

**Issue by Avocari** [SK-CERT/Taranis-NG#81]
Hello all,
I tried to start the demonstration of Taranis, but I cannot log in.

admin:admin does not work.

I used the following commands

```
docker-compose -f docker/docker-compose.yml pull
docker-compose -f docker/docker-compose.yml up --no-build
```

The website is showing, but it says wrong password/username

Thanks for the help!
Cheers,
Avocari

**Comment by dodancs** [comment]
The issue was not related to TNG but a rather bad configuration. Although, this means it is important to update the documentation.
