### ISSUE TITLE
Password data logged in plain text

### ISSUE THREAD

**Issue by ncsc-fi-kimmo** [SK-CERT/Taranis-NG#86]
Setting up I noticed this in the logs, it's good hygiene not to log passwords or any other secrets:

`TARANIS NG Auth Error (Method: POST, Resource: /api/v1/auth/login, Activity Detail: User not exists after authentication: user, Activity Data: \{"username":"user","password":"user"\})`

**Comment by ncsc-fi-kimmo** [comment]
Also in the collectors API:
`TARANIS NG Auth Error (Method: GET, Resource: /api/v1/collectors/1, Activity Detail: Incorrect api key: supersecret for external access, Activity Data: )`

**Comment by milankowww** [comment]
fixed by the latest pull request
