### ISSUE TITLE
Default credentials: User does not exist

### ISSUE THREAD

**Issue by alx-hblr** [SK-CERT/Taranis-NG#92]
I just installed TaranisNG on an UbuntuVM for testing and basically the only commands I used were those from docker/README.md (without changing any of the passwords in /docker/.env):
```
git clone https://github.com/SK-CERT/Taranis-NG.git
cd Taranis-NG
docker-compose -f docker/docker-compose.yml pull
docker-compose -f docker/docker-compose.yml up --no-build
```

Now the problem is that I can't login using the default credentials 'admin' / 'admin' or 'user' / 'user'. Did you change them recently?

**Comment by alx-hblr** [comment]
I also get a lot of [DEBUG]-messages in the terminal window, which i used to install and then start the TarnarisNG-Container, like these:
```
collectors_1  | [2022-08-31 13:40:51 +0200] [10] [DEBUG] [None] [managers.collectors_manager] Sending status update...
collectors_1  | [2022-08-31 13:40:51 +0200] [10] [DEBUG] [Errno 2] No such file or directory: '/app/storage/id.txt'
collectors_1  | [2022-08-31 13:40:51 +0200] [10] [DEBUG] [None] [managers.collectors_manager] Core responded with: HTTP 0, Cannot read collector config file.
```
And what's probably very interesting:
`core_1        | TARANIS NG Auth Error (Method: POST, Resource: /api/v1/auth/login, Activity Detail: User not exists after authentication: user, Activity Data: \{"username":"user","password":"user"\})`

`core_1        | TARANIS NG Auth Error (Method: POST, Resource: /api/v1/auth/login, Activity Detail: User not exists after authentication: admin, Activity Data: \{"username":"admin","password":"admin"\})`

**Comment by sebix** [comment]
Have a look at https://github.com/SK-CERT/Taranis-NG/issues/88#issuecomment-1194198106-permalink

**Comment by alx-hblr** [comment]
Error: No such container: taranis-ng-core-1

**Comment by alx-hblr** [comment]
Now it works, after searching the Container from your suggestions of #88 using `sudo docker container ls` i found out the container got renamed to "taranis-ng_core_1", so running `docker exec -it taranis-ng_core_1 python manage.py sample-data` fixed it, thank you
